spring:
  application:
    name: spring-gha
  profiles:
    active: dev

server:
  port : 8090

hello-message: t
alt-service: none

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans