spring:
  application:
    name: springgha
  profiles:
    active: default
  config:
#    import: optional:configserver:http://spring-config-route-phoonum-sl-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
    import: optional:configserver:http://spring-cloud-config-phoonum-sl-dev.apps.sandbox-m3.1530.p1.openshiftapps.com/
#    import: optional:configserver:http://spring-config-service:8888
#    import: optional:configserver:http://localhost:8888

server:
  port : 8080

alt-service: a
config-message: a
kube-message: a
 
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false
  
management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'