apiVersion: v1
kind: Service
metadata:
  name: spring-gha-service
  namespace: phoonum-sl-dev
spec: 
  selector:
    app: spring-gha
    deployment: spring-gha
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: main
    - protocol: TCP
      port: 9411
      targetPort: 9411
      name: zipkin
