name: build-jar
on: workflow_dispatch
jobs:
  create-jar:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Setup Java
       uses: actions/setup-java@v4
       with:
         java-version: '21'
         distribution: 'temurin'
     - name: Run test
       run: mvn clean package
     - name: Create artifact
       run: mkdir staging && cp target/*.jar result
     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
         name: Package
         path: result